### ISSUE TITLE
Not MLG Enough

### ISSUE THREAD

**Issue by SixBeeps** [TheMonsterFromTheDeep/mlgplusplus#1]
M8 got Hitmarker 'cuz there no Weed rekt skrublord

**Comment by TheMonsterFromTheDeep** [comment]
i await ur dank pull request m8

**Comment by SixBeeps** [comment]
**boi**

**Comment by SixBeeps** [comment]
U need to git(hub) gud m9 cuz oh baybee a triple! (Actually, I just made a floating point number "WEED")

**Comment by TheMonsterFromTheDeep** [comment]
@niorg2606 I can add you as a collaborator to this repo if you want :]

**Comment by SixBeeps** [comment]
> @niorg2606 I can add you as a collaborator to this repo if you want :]

That would be gr8!

**Comment by TheMonsterFromTheDeep** [comment]
yu r invited! XDDDDDD

I don't know why I didn't see your reply sooner - I guess I wasn't paying attention.
